name: Metrics Comparison and Post Comment
on:
  workflow_run:
    workflows: ["E2E Tests"]
    types: [completed]
permissions:
  contents: read
  pull-requests: write
jobs:
  metrics-comparison:
    name: Compare Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Install adm-zip
        run: npm install adm-zip

      - name: Download all metrics artifacts from triggering workflow
        id: download-artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const workflowRunId = context.payload.workflow_run.id;
            
            // List all artifacts from the triggering workflow run
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id: workflowRunId,
            });
            
            // Build artifact map with download URLs
            const artifactMap = {};
            artifacts.data.artifacts.forEach(artifact => {
              artifactMap[artifact.name] = `https://github.com/${owner}/${repo}/actions/runs/${workflowRunId}/artifacts/${artifact.id}`;
            });
            
            // Write map to file
            const fs = require('fs');
            const path = require('path');
            fs.writeFileSync(path.join(process.env.GITHUB_WORKSPACE, '.metrics/artifact_map.json'), JSON.stringify(artifactMap));
            
            // Download and extract each artifact
            const AdmZip = require('adm-zip');
            
            let artifactLinks = {};
            
            for (const artifact of artifacts.data.artifacts) {
              const download = await github.rest.actions.downloadArtifact({
                owner,
                repo,
                artifact_id: artifact.id,
                archive_format: 'zip',
              });
            
              const zip = new AdmZip(Buffer.from(download.data));
              zip.extractAllTo(path.join(process.env.GITHUB_WORKSPACE, '.metrics', artifact.name), true);
              console.log(`Extracted artifact: ${artifact.name}`);
            
              // Store the artifact URL
              artifactLinks[artifact.name] = `https://github.com/${owner}/${repo}/suites/${{ github.run_id }}/artifacts/${artifact.id}`;
            }
            
            // Set output with all artifact links as JSON
            core.setOutput('artifact_links', JSON.stringify(artifactLinks));
            
            // Extract PR number (existing code)
            let prNumber = null;
            const pullRequest = await github.rest.pulls.list({
              owner,
              repo,
              head: `${context.payload.workflow_run.head_repository.full_name}:${context.payload.workflow_run.head_branch}`,
            });
            
            if (pullRequest.data.length > 0) {
              prNumber = pullRequest.data[0].number;
            } else {
              // Fallback to commit SHA if needed
              const commitSha = context.payload.workflow_run.head_sha;
              const prsForCommit = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner,
                repo,
                commit_sha: commitSha,
              });
              if (prsForCommit.data.length > 0) {
                prNumber = prsForCommit.data[0].number;
              }
            }
            
            if (prNumber) {
              console.log(`Found PR Number: ${prNumber}`);
              core.setOutput('pr_number', prNumber);
            } else {
              console.log('Could not determine PR number. Skipping comment.');
              core.setFailed('Could not determine PR number for commenting.');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: success() && steps.download-artifacts.outputs.pr_number
        run: |
          python3 -m pip install prometheus-client
          npm install @actions/core @actions/github

      - name: Compare metrics and generate summary
        if: success() && steps.download-artifacts.outputs.pr_number
        id: compare-metrics
        shell: bash
        run: |
          ARTIFACT_LINKS=$(echo '${{ steps.download-artifacts.outputs.artifact_links }}' | jq -r '.')
          
          DIFF_ARTIFACT_LINK=$(echo "$ARTIFACT_LINKS" | jq -r 'to_entries[] | select(.key | startswith("diff_")) | .value' | head -1)
          
          if [ -z "$DIFF_ARTIFACT_LINK" ]; then
            DIFF_ARTIFACT_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi
          
          LINK_TO_ARTIFACT="$DIFF_ARTIFACT_LINK" bash ./scripts/e2e/metrics_summary.sh

      - name: Post PR comment with combined metrics summary
        if: steps.compare-metrics.outputs.DIFF_FOUND == 'true' && steps.download-artifacts.outputs.pr_number
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ./.metrics/combined_summary.md
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          comment-tag: "## Metrics Comparison Summary"
          pr-number: ${{ steps.download-artifacts.outputs.pr_number }}