name: Metrics Comparison and Post Comment
on:
  workflow_run:
    workflows: ["E2E Tests"]
    types: [completed]
permissions:
  contents: read
  pull-requests: write
jobs:
  metrics-comparison:
    name: Compare Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Install adm-zip
        run: npm install adm-zip

      - name: Download all metrics artifacts from triggering workflow
        id: download-artifacts
        run: node .github/scripts/download-artifacts-and-get-pr.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: success() && steps.download-artifacts.outputs.pr_number
        run: |
          python3 -m pip install prometheus-client
          npm install @actions/core @actions/github

      - name: Compare metrics and generate summary
        if: success() && steps.download-artifacts.outputs.pr_number
        id: compare-metrics
        shell: bash
        run: |
          bash ./scripts/e2e/metrics_summary.sh
        env:
          LINK_TO_ARTIFACT: "https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"

      - name: Post PR comment with combined metrics summary
        if: steps.compare-metrics.outputs.DIFF_FOUND == 'true' && steps.download-artifacts.outputs.pr_number
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ./.metrics/combined_summary.md
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          comment-tag: "## Metrics Comparison Summary"
          pr-number: ${{ steps.download-artifacts.outputs.pr_number }}