name: E2E Tests

on:
  merge_group:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: combined-cit-${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  elasticsearch:
    uses: ./.github/workflows/ci-e2e-elasticsearch.yml

  upload_pr_number:
    name: Save and Upload PR Number as Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number as artifact
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.number }}" > pr_number.txt
      - name: Upload PR number artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt